version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle build

  release:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: auto shipit
#      - run: gradle publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseRepository
#      - run: gradle orchidDeploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - release:
        requires:
          - build
        filters:
          branches:
            only:
              - master